# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/blade2/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/zte/blade2/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/zte/blade2/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/zte/blade2/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/zte/blade2/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/zte/blade2/proprietary/lib/libdll.so:system/lib/libdll.so \
    vendor/zte/blade2/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/zte/blade2/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/zte/blade2/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/zte/blade2/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/zte/blade2/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/zte/blade2/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/zte/blade2/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/zte/blade2/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/zte/blade2/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/zte/blade2/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/zte/blade2/proprietary/lib/libSimCardAuth.so:system/lib/libSimCardAuth.so \
    vendor/zte/blade2/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/zte/blade2/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/zte/blade2/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/zte/blade2/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/zte/blade2/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/zte/blade2/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/zte/blade2/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/zte/blade2/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/zte/blade2/proprietary/bin/hciattach:system/bin/hciattach \
    vendor/zte/blade2/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/zte/blade2/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/zte/blade2/proprietary/bin/BCM4330B1_0243.0000_ZTE_P736V.hcd:system/bin/BCM4330B1_0243.0000_ZTE_P736V.hcd \
    vendor/zte/blade2/proprietary/etc/BCM4330B1_002.001.032.0518.0520.hcd:system/etc/BCM4330B1_002.001.032.0518.0520.hcd \
    vendor/zte/blade2/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/zte/blade2/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/zte/blade2/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/zte/blade2/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/zte/blade2/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/zte/blade2/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/zte/blade2/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/zte/blade2/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/zte/blade2/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/zte/blade2/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/zte/blade2/proprietary/lib/libloc_api-rpc-qc.so:system/lib/libloc_api-rpc-qc.so \
    vendor/zte/blade2/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so \
    vendor/zte/blade2/proprietary/bin/akmd8962:system/bin/akmd8962 \
    vendor/zte/blade2/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/zte/blade2/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/zte/blade2/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
    vendor/zte/blade2/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/zte/blade2/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/zte/blade2/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/zte/blade2/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/zte/blade2/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/zte/blade2/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/zte/blade2/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/zte/blade2/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/zte/blade2/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/zte/blade2/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/zte/blade2/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/zte/blade2/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/zte/blade2/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
    vendor/zte/blade2/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/zte/blade2/proprietary/lib/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \
    vendor/zte/blade2/proprietary/lib/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \
    vendor/zte/blade2/proprietary/lib/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \
    vendor/zte/blade2/proprietary/lib/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \
    vendor/zte/blade2/proprietary/lib/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/zte/blade2/proprietary/lib/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so \
    vendor/zte/blade2/proprietary/lib/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so \
    vendor/zte/blade2/proprietary/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
    vendor/zte/blade2/proprietary/lib/libOmxrv9Dec.so:system/lib/libOmxrv9Dec.so \
    vendor/zte/blade2/proprietary/lib/libdivxdrmdecrypt.so:system/lib/libdivxdrmdecrypt.so \
    vendor/zte/blade2/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/zte/blade2/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/zte/blade2/proprietary/lib/libmmparser_divxdrmlib.so:system/lib/libmmparser_divxdrmlib.so
